### ISSUE TITLE
Rethink growth cards

### ISSUE THREAD

**Issue by dedetheprogrammer** [UNIZAR-30226-2023-10/CatanBackend#3]
Now the growth cards deck is inside the game board:
```js
game.board = {
  biomes: biomes,
  thief_biome: -1,
  nodes: nodes,
  roads: edges,
  buildings: new Set(),
  growth_deck: {
      'Caballeros': 14,
      'Carreteras': 2,
      'Monopolio': 2,
      'Descubrimiento': 2,
      'Punto': 5
}
```

@Rael167, we need to refactor every function that make use of this deck

**Comment by Rael167** [comment]
We don't need this. We need a random vector of growth_deck.

`return {
        biomes: biomes,
        thief_biome: -1,
        nodes: nodes,
        roads: edges,
        buildings: new Set(),
        growth_deck: [],
    }`
